version: "3"
services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node1
    ports:
      - "3222:22"
      - "8081:80"

  node2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node2
    ports:
      - "3223:22"
      - "8082:80"
